package com.sd.prj_prova_cad_inscricao.views;


import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author natsa
 */
public class Nsr_FormInscricoesEstados extends javax.swing.JFrame {


   /* private void preencherTabela(List<InscriçoesEstados> lstInscricoesEstados {
        DefaultTableModel tabelaProdutos = (DefaultTableModel) tabInscricoes.getModel();
        tabInscricoes.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabInscricoes.getColumnModel().getColumn(1).setPreferredWidth(100);
        
        tabelaProdutos.setNumRows(0);

        lstInscricoesEstados.forEach(InscricaoEstado -> {
            tabelaProdutos.addRow(new Object[]{InscricaoEstado.getEstado(),
                InscricaoEstado.getNsr_nome()});
        });

        tabInscricoes.addMouseListener(new MouseAdapter() {
            int LinhaSelecionada;
            //int ColunaSelecionada;
            int CodigoSelecionado;

            @Override
            public void mousePressed(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    LinhaSelecionada = tabInscricoes.getSelectedRow();

                    CodigoSelecionado = (int) (tabInscricoes.getValueAt(LinhaSelecionada, 0));

                    Nsr_FormIncricaoEstado FormIns = new Nsr_FormIncricaoEstado(CodigoSelecionado);
                    FormIns.setVisible(true);
                }
            }
        });

    }*/

    TableRowSorter<TableModel> sorter;

    public Nsr_FormInscricoesEstados() {
        initComponents();
        // Instala o TableRowSorter.
        sorter = new TableRowSorter<TableModel>(tabInscricoes.getModel());
        tabInscricoes.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabInscricoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RELATÓRIO DE PRODUTOS");

        tabInscricoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Estados", "Número de Inscriçoes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabInscricoes.setShowGrid(true);
        jScrollPane1.setViewportView(tabInscricoes);
        if (tabInscricoes.getColumnModel().getColumnCount() > 0) {
            tabInscricoes.getColumnModel().getColumn(0).setResizable(false);
            tabInscricoes.getColumnModel().getColumn(1).setResizable(false);
            tabInscricoes.getColumnModel().getColumn(2).setResizable(false);
            tabInscricoes.getColumnModel().getColumn(3).setResizable(false);
            tabInscricoes.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RELATÓRIO DE INSCRIÇOES POR ESTADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nsr_FormInscricoesEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nsr_FormInscricoesEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nsr_FormInscricoesEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nsr_FormInscricoesEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nsr_FormInscricoesEstados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTable tabInscricoes;
    // End of variables declaration//GEN-END:variables
}
