package Forms;

import BO.Nsr_Venda_ProdutoBO;
import Objetos.Nsr_Venda_Produto;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author natsa
 */
public class Nsr_RelatDeQtdValorVendProduto extends javax.swing.JFrame {

    private MaskFormatter mftDataInicio, mftDataFim;
    Nsr_Venda_ProdutoBO vpBO = new Nsr_Venda_ProdutoBO();
    private List<Nsr_Venda_Produto> nsr_lstVendaProdutos;

    private void Nsr_pesquisar() {
        List<Nsr_Venda_Produto> nsr_lstVendaProdutos;

        String nsr_nome = nsr_txtConsNome.getText().trim();
        String nsr_dataInicio = nsr_txtDataInicial.getText().trim();
        String nsr_dataFim = nsr_txtDataFinal.getText().trim();

        if (!nsr_nome.isEmpty() && (nsr_dataInicio.length() == 4)
                && (nsr_dataFim.length() == 4)) {
            nsr_lstVendaProdutos = vpBO.getNsr_Venda_Produtos(nsr_nome);
            Nsr_preencherTabela(nsr_lstVendaProdutos);
        } else if ((!nsr_nome.isEmpty()) && (nsr_dataInicio.length() != 4)
                && (nsr_dataFim.length() != 4)) {
            nsr_lstVendaProdutos = vpBO.getNsr_Venda_Produtos(nsr_nome, nsr_dataInicio, nsr_dataFim);
            Nsr_preencherTabela(nsr_lstVendaProdutos);
        } else if ((nsr_dataInicio.length() != 4) && (nsr_dataFim.length() != 4)) {
            nsr_lstVendaProdutos = vpBO.getNsr_Venda_Produtos1(nsr_dataInicio, nsr_dataFim);
            Nsr_preencherTabela(nsr_lstVendaProdutos);
        } else {
            nsr_lstVendaProdutos = vpBO.getNsr_Produtos1();
            Nsr_preencherTabela(nsr_lstVendaProdutos);
        }
    }

    private void Nsr_preencherTabela(List<Nsr_Venda_Produto> nsr_lstVendaProdutos) {
        DefaultTableModel tabelaProdutoVendidos = (DefaultTableModel) nsr_tabProdutoVendido.getModel();
        nsr_tabProdutoVendido.getColumnModel().getColumn(0).setPreferredWidth(10);
        nsr_tabProdutoVendido.getColumnModel().getColumn(1).setPreferredWidth(100);
        nsr_tabProdutoVendido.getColumnModel().getColumn(2).setPreferredWidth(60);
        nsr_tabProdutoVendido.getColumnModel().getColumn(3).setPreferredWidth(50);
        nsr_tabProdutoVendido.getColumnModel().getColumn(4).setPreferredWidth(100);
        nsr_tabProdutoVendido.getColumnModel().getColumn(5).setPreferredWidth(100);
        nsr_tabProdutoVendido.getColumnModel().getColumn(6).setPreferredWidth(100);
        tabelaProdutoVendidos.setNumRows(0);

        nsr_lstVendaProdutos.forEach(nsr_itemProdutoVendido -> {
            tabelaProdutoVendidos.addRow(new Object[]{nsr_itemProdutoVendido.getNsr_produto().getNsr_idProduto(),
                nsr_itemProdutoVendido.getNsr_produto().getNsr_nome(), nsr_itemProdutoVendido.getNsr_produto().getNsr_marca(),
                nsr_itemProdutoVendido.getNsr_produto().getNsr_modelo(), nsr_itemProdutoVendido.getNsr_produto().getNsr_valor(),
                nsr_itemProdutoVendido.getNsr_quantidade(), nsr_itemProdutoVendido.getNsr_total_item()});
        });

    }

    TableRowSorter<TableModel> sorter;

    public Nsr_RelatDeQtdValorVendProduto() {
        initComponents();
        // Instala o TableRowSorter.
        sorter = new TableRowSorter<TableModel>(nsr_tabProdutoVendido.getModel());
        nsr_tabProdutoVendido.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nsr_tabProdutoVendido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nsr_txtConsNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        try
        {
            mftDataInicio = new MaskFormatter("##/##/####");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel usar a mascara!" );
        }
        nsr_txtDataInicial = new JFormattedTextField(mftDataInicio);
        jLabel4 = new javax.swing.JLabel();
        try
        {
            mftDataFim = new MaskFormatter("##/##/####");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel usar a mascara!" );
        }
        nsr_txtDataFinal = new JFormattedTextField(mftDataFim);
        nsr_btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RELATÓRIO DE QTD VALOR VEND. POR PRODUTO");

        nsr_tabProdutoVendido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Marca", "Modelo", "Valor Item", "Qtd Vendida", "Valor total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nsr_tabProdutoVendido.setShowGrid(true);
        nsr_tabProdutoVendido.setShowHorizontalLines(true);
        nsr_tabProdutoVendido.setShowVerticalLines(true);
        jScrollPane1.setViewportView(nsr_tabProdutoVendido);
        if (nsr_tabProdutoVendido.getColumnModel().getColumnCount() > 0) {
            nsr_tabProdutoVendido.getColumnModel().getColumn(0).setResizable(false);
            nsr_tabProdutoVendido.getColumnModel().getColumn(1).setResizable(false);
            nsr_tabProdutoVendido.getColumnModel().getColumn(2).setResizable(false);
            nsr_tabProdutoVendido.getColumnModel().getColumn(3).setResizable(false);
            nsr_tabProdutoVendido.getColumnModel().getColumn(4).setResizable(false);
            nsr_tabProdutoVendido.getColumnModel().getColumn(5).setResizable(false);
            nsr_tabProdutoVendido.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RELATÓRIO DE QTD E VALOR VEND. PRODUTO");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar produto"));

        jLabel2.setText("Produto:");

        nsr_txtConsNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nsr_txtConsNomeCaretUpdate(evt);
            }
        });

        jLabel3.setText("Período de:");

        jLabel4.setText("até");

        nsr_btnConsultar.setText("Consultar");
        nsr_btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nsr_btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nsr_txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nsr_txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nsr_txtConsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(301, 301, 301))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nsr_btnConsultar)
                        .addGap(426, 426, 426))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nsr_txtConsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nsr_txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(nsr_txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nsr_btnConsultar)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Pesquisar produtos");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nsr_btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nsr_btnConsultarActionPerformed
        // TODO add your handling code here:
        Nsr_pesquisar();
    }//GEN-LAST:event_nsr_btnConsultarActionPerformed

    private void nsr_txtConsNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nsr_txtConsNomeCaretUpdate
        // TODO add your handling code here:
        Nsr_pesquisar();
    }//GEN-LAST:event_nsr_txtConsNomeCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nsr_RelatDeQtdValorVendProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nsr_RelatDeQtdValorVendProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nsr_RelatDeQtdValorVendProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nsr_RelatDeQtdValorVendProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nsr_RelatDeQtdValorVendProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nsr_btnConsultar;
    private javax.swing.JTable nsr_tabProdutoVendido;
    private javax.swing.JTextField nsr_txtConsNome;
    private javax.swing.JTextField nsr_txtDataFinal;
    private javax.swing.JTextField nsr_txtDataInicial;
    // End of variables declaration//GEN-END:variables
}
