package Forms;

import BO.Nsr_ProdutoBO;
import Objetos.Nsr_Produto;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.regex.PatternSyntaxException;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author natsa
 */
public class Nsr_FormRelatProdutos extends javax.swing.JFrame {

    Nsr_ProdutoBO pBO = new Nsr_ProdutoBO();

    private void Nsr_pesquisar() {
        List<Nsr_Produto> nsr_lstProdutos;

        String nsr_nome = nsr_txtConsNome.getText().trim();
        String nsr_marca = nsr_txtConsMarca.getText().trim();
        String nsr_modelo = nsr_txtConsModelo.getText().trim();
        
        if (!nsr_nome.isEmpty() && nsr_marca.isEmpty() && nsr_modelo.isEmpty()) {
            nsr_lstProdutos = pBO.getNsr_Produtos(nsr_nome);
            preencherTabela(nsr_lstProdutos);
        } else if(nsr_nome.isEmpty() && !nsr_marca.isEmpty() && nsr_modelo.isEmpty()){
            nsr_lstProdutos = pBO.getNsr_Produtos1(nsr_marca);
            preencherTabela(nsr_lstProdutos);
        }else if(nsr_nome.isEmpty() && nsr_marca.isEmpty() && !nsr_modelo.isEmpty()){
            nsr_lstProdutos = pBO.getNsr_Produtos2(nsr_modelo);
            preencherTabela(nsr_lstProdutos);
        } else if(!nsr_nome.isEmpty() && !nsr_marca.isEmpty() && nsr_modelo.isEmpty()){
            nsr_lstProdutos = pBO.getNsr_Produtos(nsr_nome, nsr_marca);
            preencherTabela(nsr_lstProdutos);
        } else if(!nsr_nome.isEmpty() && nsr_marca.isEmpty() && !nsr_modelo.isEmpty()){
            nsr_lstProdutos = pBO.getNsr_Produtos1(nsr_nome, nsr_modelo);
            preencherTabela(nsr_lstProdutos);
        }else if(nsr_nome.isEmpty() && !nsr_marca.isEmpty() && !nsr_modelo.isEmpty()){
            nsr_lstProdutos = pBO.getNsr_Produtos2(nsr_marca, nsr_modelo);
            preencherTabela(nsr_lstProdutos);
        } else if(!nsr_nome.isEmpty() && !nsr_marca.isEmpty() && !nsr_modelo.isEmpty()){
            nsr_lstProdutos = pBO.getNsr_Produtos(nsr_nome, nsr_marca, nsr_modelo);
            preencherTabela(nsr_lstProdutos);
        }  else {
            nsr_lstProdutos = pBO.getNsr_Produtos();
            preencherTabela(nsr_lstProdutos);
        }
    }

    private void preencherTabela(List<Nsr_Produto> nsr_lstProdutos) {
        DefaultTableModel tabelaProdutos = (DefaultTableModel) tabProdutos.getModel();
        tabProdutos.getColumnModel().getColumn(0).setPreferredWidth(10);
        tabProdutos.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabProdutos.getColumnModel().getColumn(1).setPreferredWidth(60);
        tabProdutos.getColumnModel().getColumn(1).setPreferredWidth(50);
        tabProdutos.getColumnModel().getColumn(2).setPreferredWidth(10);
        tabelaProdutos.setNumRows(0);

        nsr_lstProdutos.forEach(nsr_itemProduto -> {
            tabelaProdutos.addRow(new Object[]{nsr_itemProduto.getNsr_idProduto(),
                nsr_itemProduto.getNsr_nome(), nsr_itemProduto.getNsr_marca(), nsr_itemProduto.getNsr_modelo(), nsr_itemProduto.getNsr_valor()});
        });

        tabProdutos.addMouseListener(new MouseAdapter() {
            int LinhaSelecionada;
            //int ColunaSelecionada;
            int CodigoSelecionado;

            @Override
            public void mousePressed(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    LinhaSelecionada = tabProdutos.getSelectedRow();

                    CodigoSelecionado = (int) (tabProdutos.getValueAt(LinhaSelecionada, 0));

                    Nsr_FormCadastroProduto FormCadP = new Nsr_FormCadastroProduto(CodigoSelecionado);
                    FormCadP.setVisible(true);
                }
            }
        });

    }

    TableRowSorter<TableModel> sorter;

    public Nsr_FormRelatProdutos() {
        initComponents();
        // Instala o TableRowSorter.
        sorter = new TableRowSorter<TableModel>(tabProdutos.getModel());
        tabProdutos.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nsr_txtConsNome = new javax.swing.JTextField();
        nsr_btnConsultar = new javax.swing.JButton();
        nsr_txtConsMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nsr_txtConsModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RELATÓRIO DE PRODUTOS");

        tabProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Marca", "Modelo", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabProdutos.setShowGrid(true);
        jScrollPane1.setViewportView(tabProdutos);
        if (tabProdutos.getColumnModel().getColumnCount() > 0) {
            tabProdutos.getColumnModel().getColumn(0).setResizable(false);
            tabProdutos.getColumnModel().getColumn(1).setResizable(false);
            tabProdutos.getColumnModel().getColumn(2).setResizable(false);
            tabProdutos.getColumnModel().getColumn(3).setResizable(false);
            tabProdutos.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RELATÓRIO DE PRODUTOS");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar produtos"));

        jLabel2.setText("Nome:");

        nsr_txtConsNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nsr_txtConsNomeCaretUpdate(evt);
            }
        });

        nsr_btnConsultar.setText("Consultar");
        nsr_btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nsr_btnConsultarActionPerformed(evt);
            }
        });

        nsr_txtConsMarca.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nsr_txtConsMarcaCaretUpdate(evt);
            }
        });

        jLabel3.setText("Marca:");

        nsr_txtConsModelo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nsr_txtConsModeloCaretUpdate(evt);
            }
        });

        jLabel4.setText("Modelo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nsr_btnConsultar)
                .addGap(295, 295, 295))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nsr_txtConsModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nsr_txtConsMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nsr_txtConsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nsr_txtConsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(nsr_txtConsMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nsr_txtConsModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(nsr_btnConsultar)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nsr_btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nsr_btnConsultarActionPerformed
        // TODO add your handling code here:
        Nsr_pesquisar();
    }//GEN-LAST:event_nsr_btnConsultarActionPerformed

    private void nsr_txtConsNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nsr_txtConsNomeCaretUpdate
        // TODO add your handling code here:
        Nsr_pesquisar();
    }//GEN-LAST:event_nsr_txtConsNomeCaretUpdate

    private void nsr_txtConsMarcaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nsr_txtConsMarcaCaretUpdate
        // TODO add your handling code here:
        Nsr_pesquisar();
    }//GEN-LAST:event_nsr_txtConsMarcaCaretUpdate

    private void nsr_txtConsModeloCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nsr_txtConsModeloCaretUpdate
        // TODO add your handling code here:
        Nsr_pesquisar();
    }//GEN-LAST:event_nsr_txtConsModeloCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nsr_FormRelatProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nsr_FormRelatProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nsr_FormRelatProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nsr_FormRelatProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nsr_FormRelatProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JButton nsr_btnConsultar;
    private javax.swing.JTextField nsr_txtConsMarca;
    private javax.swing.JTextField nsr_txtConsModelo;
    private javax.swing.JTextField nsr_txtConsNome;
    private javax.swing.JTable tabProdutos;
    // End of variables declaration//GEN-END:variables
}
